Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Controllers/AdminController.cs
using Barometer_ASP_NET.FileFactory;
using Barometer_ASP_NET.Wrappers;
using BarometerDataAccesLayer.Database;
using BarometerDataAccesLayer;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Linq;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Barometer_ASP_NET.Filters;

namespace Barometer_ASP_NET.Controllers
{
    [AuthFilter("admin")]
    public class AdminController : Controller
    {
        AdminDashboardWrapper wrapper = new AdminDashboardWrapper(CurrentUser.getInstance().Studentnummer);
        //
        // GET: /Admin/

        public ActionResult Index()
        {

            return RedirectToAction("Dashboard");
        }
    

        public ActionResult Dashboard()
        {
            return View(wrapper);
        }

        DatabaseClassesDataContext db = DatabaseFactory.getInstance().getDataContext();

        public ActionResult Barotemplate()
        {
            int debug_id = (Request["template_id"] == null) ? 0 : Convert.ToInt32(Request["template_id"]);
            ViewBag.debug_id = debug_id;
            return View();
        }

        public ActionResult Create()
        {
            CreateProjectWrapper wrapper = new CreateProjectWrapper();
            return View(wrapper);
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            if (collection.Count != 0)
            {
                BarometerDataAccesLayer.DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();
                BarometerDataAccesLayer.Project insertProject = new BarometerDataAccesLayer.Project();
                BarometerDataAccesLayer.ProjectOwner me = new BarometerDataAccesLayer.ProjectOwner();
                var ownerInfo =
                    from u in context.Users
                    where u.student_number == CurrentUser.getInstance().Studentnummer
                    select u;
                me.User = ownerInfo.First();
                insertProject.name = collection.GetValue("FormProject.name").AttemptedValue;
                insertProject.description = collection.GetValue("FormProject.description").AttemptedValue;
                insertProject.start_date = DateTime.ParseExact(collection.GetValue("FormProject.start_date").AttemptedValue, "dd-MM-yyyy", CultureInfo.InvariantCulture);
                insertProject.end_date = DateTime.ParseExact(collection.GetValue("FormProject.end_date").AttemptedValue, "dd-MM-yyyy", CultureInfo.InvariantCulture);
                insertProject.ProjectOwners.Add(me);
                insertProject.status_name = "Pending";
                if (Request.Files.Count != 0)
                {
                    HttpPostedFileBase fileBase = Request.Files[0];
                    StudentExcel studentExcel = new StudentExcel(insertProject);
                    studentExcel.Import(fileBase.InputStream);


                    insertProject.baro_template_id = int.Parse(collection.GetValue("FormProject.baro_template_id").AttemptedValue);

                    string[] reportDateNames = collection.GetValue("reportDateName[]").AttemptedValue.Split(',');
                    string[] reportStartDates = collection.GetValue("reportStartDate[]").AttemptedValue.Split(',');
                    string[] reportEndDates = collection.GetValue("reportEndDate[]").AttemptedValue.Split(',');
                    EntitySet<BarometerDataAccesLayer.ProjectReportDate> reportDateEntities = new EntitySet<BarometerDataAccesLayer.ProjectReportDate>();

                    int counter = 0;
                    foreach (string reportDateName in reportDateNames)
                    {
                        BarometerDataAccesLayer.ProjectReportDate tmpReportDate = new BarometerDataAccesLayer.ProjectReportDate();
                        tmpReportDate.Project = insertProject;
                        tmpReportDate.week_label = reportDateName;
                        tmpReportDate.start_date = DateTime.Parse(reportStartDates[counter]);
                        tmpReportDate.end_date = DateTime.Parse(reportEndDates[counter]);
                        context.ProjectReportDates.InsertOnSubmit(tmpReportDate);
                        counter++;
                    }
                    context.SubmitChanges();
                }
            }
            return RedirectToAction("List");
        }

        public ActionResult Detail()
        {
            return View();
        }

        public ActionResult List()
        {
            return View(wrapper);
        }

        public ActionResult ListProjectGroup(int projectId)
        {
            AdminProjectGroupListWrapper wrapper = new AdminProjectGroupListWrapper(projectId);
            return View(wrapper);
        }

        public ActionResult ProjectGroups(int groupId)
        {
            AdminProjectGroupViewWrapper wrapper = new AdminProjectGroupViewWrapper(groupId);
            return View(wrapper);
        }

        
        [AuthFilter("admod")]        
        public ActionResult Student(int studentId)
        {
            BarometerDataAccesLayer.DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();
            var student =
                from u in context.Users
                where u.id == studentId
                select u;
            if (student.ToList().Count > 0)
            {
                return View(student.First());
            }
            else
            {
                throw new DataException("No data found");
            }
        }

        public ActionResult StudentForm(FormCollection collection)
        {

            int studentNumber = int.Parse(collection.GetValue("student").AttemptedValue);
            //UserDashboardWrapper userwrap = new UserDashboardWrapper(studentNumber);

            BarometerDataAccesLayer.DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();
            var student =
                from u in context.Users
                where u.student_number == studentNumber
                select u.id;
            int studentId = student.First();
            return RedirectToAction("Dashboard", "User", new { studentId = studentNumber});


        }

        public ActionResult DeleteProject(int projectId)
        {
            BarometerDataAccesLayer.DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();
            var resultProjects =
                from p in context.Projects
                where p.id == projectId
                select p;

            context.Projects.DeleteOnSubmit(resultProjects.First());
            context.SubmitChanges();

            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult AddStudent(FormCollection collection)
        {
            int studentIdToAdd = int.Parse(collection.GetValue("student").AttemptedValue);
            int projectId = int.Parse(collection.GetValue("projectID").AttemptedValue);
            int groupId = int.Parse(collection.GetValue("groupID").AttemptedValue);
            DAOStudent studentdao = DatabaseFactory.getInstance().getDAOStudent();
            DAOProject projectdao = DatabaseFactory.getInstance().getDAOProject();
            BarometerDataAccesLayer.User studentUser = studentdao.getStudentInfo(studentIdToAdd);
            IEnumerable<BarometerDataAccesLayer.ProjectMember> member = studentUser.ProjectMembers.Where(pm => pm.project_group_id == groupId);
            if (member.Count() == 0)
            {
                BarometerDataAccesLayer.ProjectMember pMember = new BarometerDataAccesLayer.ProjectMember();
                pMember.User = studentUser;
                pMember.project_group_id = groupId;
                BarometerDataAccesLayer.DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();
                context.ProjectMembers.InsertOnSubmit(pMember);
                context.SubmitChanges();
            }

            return RedirectToAction("ProjectGroups", new { groupId = groupId });
        }
    }
}

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Controllers/ManagementController.cs
using Barometer_ASP_NET.Filters;
using BarometerDataAccesLayer;
using BarometerDataAccesLayer.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Barometer_ASP_NET.Controllers
{
    [AuthFilter("manager")]
    public class ManagementController : Controller
    {
        //
        // GET: /Management/
        DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();

        public ActionResult List()
        {
            IQueryable<User> users = context.Users.Where(u => u.id > 0);
            return View(users);
        }

        //
        // GET: /Management/Details/5

        public ActionResult Details(int id)
        {
            User user = context.Users.Where(u => u.id == id).FirstOrDefault();
            return View(user);
        }

        //
        // GET: /Management/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Management/Create

        [HttpPost]
        public ActionResult Create(User collection)
        {
            try
            {
                context.Users.InsertOnSubmit(collection);
                context.SubmitChanges();
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Management/Edit/5

        public ActionResult Edit(int id)
        {
            User user = context.Users.Where(u => u.id == id).FirstOrDefault();
            return View(user);
        }

        //
        // POST: /Management/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, User collection)
        {
            try
            {
                User user = context.Users.Where(u => u.id == id).Single();
                user.id = collection.id;
                user.firstname = collection.firstname;
                user.lastname = collection.lastname;
                user.profile_image = collection.profile_image;
                user.rol_name = collection.rol_name;
                user.student_number = collection.student_number;
                user.email = collection.email;
                context.SubmitChanges();
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Management/Delete/5

        public ActionResult Delete(int id)
        {
            User user = context.Users.Where(u => u.id == id).FirstOrDefault();
            context.Users.DeleteOnSubmit(user);
            context.SubmitChanges();
            return RedirectToAction("List");
        }

        //
        // POST: /Management/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Controllers/ModeratorController.cs
using Barometer_ASP_NET.Filters;
using Barometer_ASP_NET.Wrappers;
using BarometerDataAccesLayer.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Barometer_ASP_NET.Controllers
{
    [AuthFilter("moderator")]
    public class ModeratorController : Controller
    {
        ModeratorDashboardWrapper wrapper = new ModeratorDashboardWrapper(CurrentUser.getInstance().Studentnummer); 
        //
        // GET: /Moderator/

        public ActionResult Dashboard()
        {
            return View(wrapper);
        }

        public ActionResult StudentForm(FormCollection collection)
        {
            int studentNumber = int.Parse(collection.GetValue("student").AttemptedValue);
            BarometerDataAccesLayer.DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();
            var student =
                from u in context.Users
                where u.student_number == studentNumber
                select u.id;
            int studentId = student.First();
            return RedirectToAction("Student","Admin", new { studentId = studentId });
        }

    }
}

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Controllers/UserController.cs
using BarometerDataAccesLayer;
using BarometerDataAccesLayer.Database;
using Barometer_ASP_NET.FileFactory;
using Barometer_ASP_NET.Wrappers;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Barometer_ASP_NET.Filters;

namespace Barometer_ASP_NET.Controllers
{
    public class UserController : Controller
    {
        private DatabaseClassesDataContext db = new DatabaseClassesDataContext();
        private DAOStudent daoStudent = new DAOStudent();
        private DAOProject daoProject = new DAOProject();
        private CurrentUser curUser = CurrentUser.getInstance();


        [AuthFilter("all")]
        public ActionResult Dashboard(int studentId = 0)
        {
            //VOOR ALS JE WILT TESTEN WAT JE STUDENTNUM IS : 
            // return Content(CurrentUser.getInstance().Studentnummer.ToString());
            UserDashboardWrapper wrapper;
            if (studentId != 0)
            {
                wrapper = new UserDashboardWrapper(studentId);
            }
            else
            {
                wrapper = new UserDashboardWrapper(curUser.Studentnummer);
            }

            ViewBag.Filled = (Request["b"] == "done") ? true : false;

            return View(wrapper);
        }

        [AuthFilter("user")]
        public ActionResult Barometer(int report_id = 0)
        {
            BaroReportWrapper viewModel =
                db.ProjectReportDates
                .Where(r => r.id == report_id)
                .Select(r => new BaroReportWrapper
                {
                    ReportDate = r,
                    Project = r.Project,
                    Aspects = r.Project.BaroTemplate.BaroAspects.Where(a => a.is_head_aspect == 1).ToList()
                }).FirstOrDefault();

            if (viewModel == null)
                return HttpNotFound();

            ProjectGroup group = daoStudent.getStudentGroup(curUser.Studentnummer).First();
            if (group == null)
                return RedirectToAction("Dashboard");


            viewModel.ReporterId = curUser.StudentId;
            viewModel.Members = daoProject.getUsersInGroup(group.id).ToList();


            return View(viewModel);
        }


        [AuthFilter("all")]
        public ActionResult Project(int project_id = 0)
        {
            if (project_id == 0)
                return RedirectToAction("Projecten");
            UserProjectWrapper wrapper = new UserProjectWrapper(curUser.Studentnummer, project_id);
            return View(wrapper);
        }


        [AuthFilter("all")]
        public ActionResult Projecten()
        {
            UserDashboardWrapper wrapper = new UserDashboardWrapper(curUser.Studentnummer);
            return View(wrapper);
        }
    }
}

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Avans Barometer</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Content/js")
</head>
<body>
    <div class="container">
        <div class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Avans</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Dashboard", "Admin")</li>
                    <li class="dropdown">
                        @Html.ActionLink(HttpUtility.HtmlDecode("Projecten &#x25be;"), "List", "Admin", new { @Class = "dropdown-toggle", @Data_toggle = "dropdown" })
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Aanmaken", "Create", "Admin")</li>
                            <li>@Html.ActionLink("Overzicht", "List", "Admin")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        @Html.ActionLink(HttpUtility.HtmlDecode("Barometer templates &#x25be;"), "Barotemplate", "Admin", new { @Class = "dropdown-toggle", @Data_toggle = "dropdown" })
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Aanmaken", "Barotemplate", "Admin")</li>
                            <li>@Html.ActionLink("Overzicht", "List", "Admin")</li>
                        </ul>

                    </li>
                    <li>@Html.ActionLink("Users", "UserList", "Admin")</li>
                </ul>

                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-form navbar-right" }))
                {
                    @Html.AntiForgeryToken()
                    <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-default">Log off</a>
                }
                @if (Request.IsAuthenticated)
                {
                    <p class="navbar-text navbar-right">
                        Ingelogd als @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: null, htmlAttributes: new { @class = "navbar-link", title = "Manage" })
                    </p>
                }
                else
                {
                    <p class="navbar-text navbar-right">
                        Niet ingelogd. @Html.ActionLink("Log in", "Login", "Account", null, null)
                    </p>
                }
            </div>
            <!--/.nav-collapse -->
        </div>

        <!-- Main component for a primary marketing message or call to action -->

        @if (Request.IsAuthenticated)
        {@RenderBody();
        }
        else
        {
            <div style="visibility: hidden; width: 0; height: 0;">
                @RenderBody()
            </div>
            <h1>U bent nog niet ingelogd. Klik @Html.ActionLink("Hier", "Login", "Account", null, null) om in  te loggen.</h1>    
            
        }


    </div>


    @RenderSection("scripts", required: false)
</body>
</html>

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Avans Barometer</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/Content/js")
        
    </head>
    <body>
        <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
            @RenderBody()

        </div>
        
        
        @RenderSection("scripts", required: false)
    </body>
</html>

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Shared/_ManagementLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Avans Barometer</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Content/js")
</head>
<body>
    <div class="container">
        <div class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Avans</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Users", "List", "Management")</li>
                </ul>

                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-form navbar-right" }))
                {
                    @Html.AntiForgeryToken()
                    <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-default">Log off</a>
                }
                @if (Request.IsAuthenticated)
                {
                    <p class="navbar-text navbar-right">
                        Ingelogd als @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: null, htmlAttributes: new { @class = "navbar-link", title = "Manage" })
                    </p>
                }
                else
                {
                    <p class="navbar-text navbar-right">
                        Niet ingelogd. @Html.ActionLink("Log in", "Login", "Account", null, null)
                    </p>
                }
            </div>
            <!--/.nav-collapse -->
        </div>

        <!-- Main component for a primary marketing message or call to action -->

        @if (Request.IsAuthenticated)
        {@RenderBody();
        }
        else
        {
            <div style="visibility: hidden; width: 0; height: 0;">
                @RenderBody()
            </div>
            <h1>U bent nog niet ingelogd. Klik @Html.ActionLink("Hier", "Login", "Account", null, null) om in  te loggen.</h1>    
            
        }


    </div>


    @RenderSection("scripts", required: false)
</body>
</html>

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Shared/_ModeratorLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Avans Barometer</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Content/js")
</head>
<body>
    <div class="container">
        <div class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Avans", "Dashboard", "Moderator", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Dashboard", "Dashboard", "Moderator", null)</li>
                    <li><a href="#"></a></li>
                </ul>


                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-form navbar-right" }))
                {
                    @Html.AntiForgeryToken()
                    <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-default">Log off</a>
                }
                @if (Request.IsAuthenticated)
                {
                    <p class="navbar-text navbar-right">
                        Ingelogd als @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: null, htmlAttributes: new { @class = "navbar-link", title = "Manage" })
                    </p>
                }
                else
                {
                    <p class="navbar-text navbar-right">
                        Niet ingelogd. @Html.ActionLink("Log in", "Login", "Account", null, null)
                    </p>
                }
            </div>
            <!--/.nav-collapse -->
        </div>

        <!-- Main component for a primary marketing message or call to action -->

        @if (Request.IsAuthenticated)
        {@RenderBody();
        }
        else
        {
            <div style="visibility: hidden; width: 0; height: 0;">
                @RenderBody()
            </div>
            <h1>U bent nog niet ingelogd. Klik @Html.ActionLink("Hier", "Login", "Account", null, null) om in  te loggen.</h1>    
            
        }


    </div>


    @*        @RenderSection("scripts", required: false)*@
</body>
</html>

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Avans Barometer</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Content/js")
</head>
<body>
    <div class="container">
        <div class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Avans</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Dashboard", "User", null)</li>
                    <li>@Html.ActionLink("Projecten", "Projecten", "User", null)</li>
                </ul>

                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class= "navbar-form navbar-right" }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-default">Log off</a>
                    }
                @if(Request.IsAuthenticated){
                <p class="navbar-text navbar-right">
                    Ingelogd als @Html.ActionLink(User.Identity.Name, "Manage", "Account", routeValues: null, htmlAttributes: new { @class = "navbar-link", title = "Manage" })
                </p>
                }else
                {
                    <p class="navbar-text navbar-right">
                    Niet ingelogd. @Html.ActionLink("Log in","Login","Account",null,null)
                    </p>
                }
            </div>
            <!--/.nav-collapse -->
        </div>

        <!-- Main component for a primary marketing message or call to action -->
        
        @if(Request.IsAuthenticated){@RenderBody();}
        else
        {
           <div style="visibility:hidden;width:0;height:0;">
               @RenderBody()
           </div>
            <h1>U bent nog niet ingelogd. Klik @Html.ActionLink("Hier","Login","Account",null,null) om in  te loggen.</h1>    
            
        }


    </div>


    @RenderSection("scripts", required: false)
</body>
</html>