Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Models/ProjectGroup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Barometer_ASP_NET.Models
{
	public class ProjectGroup
	{
		public string GroupName { get; set; }
		public List<Student> Students { get; set; }

		public ProjectGroup(string groupname)
		{
			GroupName = groupname;
			Students = new List<Student>();
		}
	}
}

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Barometer_ASP_NET.Models
{
	public class Student
	{
		public string Name { get; set; }
		public string Class { get; set; }
		public int StudentNumber { get; set; }
		public List<Grade> Grades { get; set; }

		public Student(string name, string clas, int studnr)
		{
			Name = name;
			Class = clas;
			StudentNumber = studnr;
			Grades = new List<Grade>();
		}

		public void AddGrade(string crit, double grade, ProjectGroup projectGroup)
		{
			Grades.Add(new Grade(crit, grade, projectGroup));
		}
	}
}

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Areas/admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Barometer_ASP_NET.Areas.admin.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /admin/Dashboard/

        public ActionResult Dashboard()
        {
            return View();
        }

    }
}

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Controllers/AdminController.cs
using Barometer_ASP_NET.FileFactory;
using Barometer_ASP_NET.Wrappers;
using BarometerDataAccesLayer.Database;
using BarometerDataAccesLayer;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Linq;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Barometer_ASP_NET.Filters;

namespace Barometer_ASP_NET.Controllers
{
    [AuthFilter("admin")]
    public class AdminController : Controller
    {
        AdminDashboardWrapper wrapper = new AdminDashboardWrapper(CurrentUser.getInstance().Studentnummer);
        //
        // GET: /Admin/

        public ActionResult Index()
        {

            return RedirectToAction("Dashboard");
        }
    

        public ActionResult Dashboard()
        {
            return View(wrapper);
        }

        DatabaseClassesDataContext db = DatabaseFactory.getInstance().getDataContext();

        public ActionResult Barotemplate()
        {
            int debug_id = (Request["template_id"] == null) ? 0 : Convert.ToInt32(Request["template_id"]);
            ViewBag.debug_id = debug_id;
            return View();
        }

        public ActionResult Create()
        {
            CreateProjectWrapper wrapper = new CreateProjectWrapper();
            return View(wrapper);
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            if (collection.Count != 0)
            {
                BarometerDataAccesLayer.DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();
                BarometerDataAccesLayer.Project insertProject = new BarometerDataAccesLayer.Project();
                BarometerDataAccesLayer.ProjectOwner me = new BarometerDataAccesLayer.ProjectOwner();
                var ownerInfo =
                    from u in context.Users
                    where u.student_number == CurrentUser.getInstance().Studentnummer
                    select u;
                me.User = ownerInfo.First();
                insertProject.name = collection.GetValue("FormProject.name").AttemptedValue;
                insertProject.description = collection.GetValue("FormProject.description").AttemptedValue;
                insertProject.start_date = DateTime.ParseExact(collection.GetValue("FormProject.start_date").AttemptedValue, "dd-MM-yyyy", CultureInfo.InvariantCulture);
                insertProject.end_date = DateTime.ParseExact(collection.GetValue("FormProject.end_date").AttemptedValue, "dd-MM-yyyy", CultureInfo.InvariantCulture);
                insertProject.ProjectOwners.Add(me);
                insertProject.status_name = "Pending";
                if (Request.Files.Count != 0)
                {
                    HttpPostedFileBase fileBase = Request.Files[0];
                    StudentExcel studentExcel = new StudentExcel(insertProject);
                    studentExcel.Import(fileBase.InputStream);


                    insertProject.baro_template_id = int.Parse(collection.GetValue("FormProject.baro_template_id").AttemptedValue);

                    string[] reportDateNames = collection.GetValue("reportDateName[]").AttemptedValue.Split(',');
                    string[] reportStartDates = collection.GetValue("reportStartDate[]").AttemptedValue.Split(',');
                    string[] reportEndDates = collection.GetValue("reportEndDate[]").AttemptedValue.Split(',');
                    EntitySet<BarometerDataAccesLayer.ProjectReportDate> reportDateEntities = new EntitySet<BarometerDataAccesLayer.ProjectReportDate>();

                    int counter = 0;
                    foreach (string reportDateName in reportDateNames)
                    {
                        BarometerDataAccesLayer.ProjectReportDate tmpReportDate = new BarometerDataAccesLayer.ProjectReportDate();
                        tmpReportDate.Project = insertProject;
                        tmpReportDate.week_label = reportDateName;
                        tmpReportDate.start_date = DateTime.Parse(reportStartDates[counter]);
                        tmpReportDate.end_date = DateTime.Parse(reportEndDates[counter]);
                        context.ProjectReportDates.InsertOnSubmit(tmpReportDate);
                        counter++;
                    }
                    context.SubmitChanges();
                }
            }
            return RedirectToAction("List");
        }

        public ActionResult Detail()
        {
            return View();
        }

        public ActionResult List()
        {
            return View(wrapper);
        }

        public ActionResult ListProjectGroup(int projectId)
        {
            AdminProjectGroupListWrapper wrapper = new AdminProjectGroupListWrapper(projectId);
            return View(wrapper);
        }

        public ActionResult ProjectGroups(int groupId)
        {
            AdminProjectGroupViewWrapper wrapper = new AdminProjectGroupViewWrapper(groupId);
            return View(wrapper);
        }

        
        [AuthFilter("admod")]        
        public ActionResult Student(int studentId)
        {
            BarometerDataAccesLayer.DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();
            var student =
                from u in context.Users
                where u.id == studentId
                select u;
            if (student.ToList().Count > 0)
            {
                return View(student.First());
            }
            else
            {
                throw new DataException("No data found");
            }
        }

        public ActionResult StudentForm(FormCollection collection)
        {

            int studentNumber = int.Parse(collection.GetValue("student").AttemptedValue);
            //UserDashboardWrapper userwrap = new UserDashboardWrapper(studentNumber);

            BarometerDataAccesLayer.DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();
            var student =
                from u in context.Users
                where u.student_number == studentNumber
                select u.id;
            int studentId = student.First();
            return RedirectToAction("Dashboard", "User", new { studentId = studentNumber});


        }

        public ActionResult DeleteProject(int projectId)
        {
            BarometerDataAccesLayer.DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();
            var resultProjects =
                from p in context.Projects
                where p.id == projectId
                select p;

            context.Projects.DeleteOnSubmit(resultProjects.First());
            context.SubmitChanges();

            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult AddStudent(FormCollection collection)
        {
            int studentIdToAdd = int.Parse(collection.GetValue("student").AttemptedValue);
            int projectId = int.Parse(collection.GetValue("projectID").AttemptedValue);
            int groupId = int.Parse(collection.GetValue("groupID").AttemptedValue);
            DAOStudent studentdao = DatabaseFactory.getInstance().getDAOStudent();
            DAOProject projectdao = DatabaseFactory.getInstance().getDAOProject();
            BarometerDataAccesLayer.User studentUser = studentdao.getStudentInfo(studentIdToAdd);
            IEnumerable<BarometerDataAccesLayer.ProjectMember> member = studentUser.ProjectMembers.Where(pm => pm.project_group_id == groupId);
            if (member.Count() == 0)
            {
                BarometerDataAccesLayer.ProjectMember pMember = new BarometerDataAccesLayer.ProjectMember();
                pMember.User = studentUser;
                pMember.project_group_id = groupId;
                BarometerDataAccesLayer.DatabaseClassesDataContext context = DatabaseFactory.getInstance().getDataContext();
                context.ProjectMembers.InsertOnSubmit(pMember);
                context.SubmitChanges();
            }

            return RedirectToAction("ProjectGroups", new { groupId = groupId });
        }
    }
}

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Barometer_ASP_NET.Controllers
{
    public class GroupController : Controller
    {
        //
        // GET: /Group/

        public ActionResult Index()
        {
            return View();
        }
        
        //Add Function

        //Remove Function

        //AddStudent Function 

        //RemoveStudent Function

        //ListStudents
    }
}

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Controllers/ProjectController.cs
using BarometerDataAccesLayer.Database;
using Barometer_ASP_NET.Models;
using BarometerDataAccesLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Barometer_ASP_NET.Controllers
{
    public class ProjectController : Controller
    {
        //
        // GET: /Project/
        public DAOStudent student = new DAOStudent();
        public DAOProject project = new DAOProject();

        public ActionResult Index()
        {
            return View();
        }

        //Detail Function
        public string ShowNameOfStudent()
        {
            Dictionary<string, string> d = student.getName(CurrentUser.getInstance().Studentnummer);//IMPORTANT, uses a test value, it needs the studentnumber when LDAP is finished.
            string s ="";
            foreach (KeyValuePair<string, string> pair in d)
            {
                 s = pair.Key + " " + pair.Value;
            }

            return s;
        }

        public string ShowNameOfProject()
        {
            string s = project.getProjectName(1);//IMPORTANT, uses a test value.
            return s;
        }

        public string ShowSummaryOfProject()
        {
            string s = project.getProjectSummary(1);
            return s;
        }

        public string ShowStartAndEndDate()
        {
            Dictionary<string, string> d = project.getStartAndEndDate(1);//IMPORTANT, uses a test value
            string s = "";
            foreach (KeyValuePair<string, string> pair in d)
            {
                s = pair.Key + " tot " + pair.Value + ")";
            }

            return s;
        }

        public ViewResult Project()
        {
            return View();
        }

    }
}

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Admin/Barolist.cshtml
 @{
    ViewBag.Title = "Barometer Lijst";
}
<div class="row">
    <div class="col-lg-12">
        <h2>Barometer templates </h2>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td>Naam</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Barometer standaard</td>
                    <td>
                        @Html.ActionLink(" ", null, null, new { @class = "glyphicon glyphicon-edit", @Href = "#" })
                        @Html.ActionLink(" ", null, null, new { @class = "glyphicon glyphicon-remove", @Href = "#" })
                    </td>
                </tr>
                <tr>
                    <td>Barometer profesional</td>
                    <td>
                        @Html.ActionLink(" ", null, null, new { @class = "glyphicon glyphicon-edit", @Href = "#" })
                        @Html.ActionLink(" ", null, null, new { @class = "glyphicon glyphicon-remove", @Href = "#" })
                    </td>
                </tr>
                <tr>
                    <td>Barometer wordfeud</td>
                    <td>
                        @Html.ActionLink(" ", null, null, new { @class = "glyphicon glyphicon-edit", @Href = "#" })
                        @Html.ActionLink(" ", null, null, new { @class = "glyphicon glyphicon-remove", @Href = "#" })
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Admin/Create.cshtml
@model Barometer_ASP_NET.Wrappers.CreateProjectWrapper
@{
    ViewBag.Title = "Barometer aanmaken";
}
<script language="javascript">
function addInput() {
    var newField = document.createElement('div');
    newField.className = "row";
    newField.innerHTML = '<div class="col-xs-4"><label class="control-label">Momentnaam</label><input type="text" class="form-control" name="reportDateName[]" /></div><div class="col-xs-4"><label class="control-label">Startdatum</label><input type="date" class="form-control" name="reportStartDate[]" /></div><div class="col-xs-4"><label class="control-label">Einddatum</label><input type="date" class="form-control" name="reportEndDate[]" /></div>';	
    document.getElementById('beoordelingsmomenten').appendChild(newField);
}
</script>
<div class="row">
    <div class="col-lg-12">
        <h2>Project</h2>
        <hr />
    </div>
    <div class="row">
        <div class="col-lg-8">
            @using (Html.BeginForm("Create", "Admin", FormMethod.Post, new { @class = "form-vertical",@runat="Server", @enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    <label class="control-label">Naam</label>
                    @Html.TextBoxFor(model => model.FormProject.name, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label class="control-label">Omschrijving</label>
                    @Html.TextBoxFor(model => model.FormProject.description, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label class="control-label">Begin datum</label>
                    @Html.TextBoxFor(model => model.FormProject.start_date, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label class="control-label">Eind datum</label>
                    @Html.TextBoxFor(model => model.FormProject.end_date, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label class="control-label">Groepsindeling</label>
                    <input type="file" class="form-control" name="groepsindeling" />
                    <span class="help-block">Toegestaande bestanden : .xls, xlsx</span>
                </div>
                <hr />
                <div class="form-group">
                    <label class="control-label">Beoordelingstemplate</label>
                    @{
                List<SelectListItem> selectItems = new List<SelectListItem>();
                foreach (BarometerDataAccesLayer.BaroTemplate template in Model.Templates)
                {
                    SelectListItem tmpItem = new SelectListItem { Text = template.template_name, Value = template.id.ToString() };
                    selectItems.Add(tmpItem);
                }
                    }
                    @Html.DropDownListFor(model => model.FormProject.baro_template_id, selectItems, new { @class = "form-control" })
                </div>
                <div class="form-group" id="beoordelingsmomenten">
                    <label class="control-label">Beoordelings momenten</label>
                    <div class="row">
                        <div class="col-xs-4">
                            <label class="control-label">Momentnaam</label>
                            <input type="text" class="form-control" name="reportDateName[]" />
                        </div>
                        <div class="col-xs-4">
                            <label class="control-label">Startdatum (JJJJ-MM-DD)</label>
                            <input type="date" class="form-control" name="reportStartDate[]" />
                        </div>

                        <div class="col-xs-4">
                            <label class="control-label">Einddatum (JJJJ-MM-DD)</label>
                            <input type="date" class="form-control" name="reportEndDate[]" />
                        </div>
                    </div>
                 </div>
                 <a href="#beoordelingsmomenten" onclick="addInput()" class="btn btn-default">Voeg veld toe</a>
                <hr />
                <div class="form-group">
                    <input type="submit" value="Opslaan" class="btn btn-primary" />
                </div>


            }
        </div>
    </div>
</div>

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Admin/Dashboard.cshtml
@model Barometer_ASP_NET.Wrappers.AdminDashboardWrapper
@{
    ViewBag.Title = "Dashboard";
}
<div class="row">
    <div class="col-lg-6">
        <h2>Groepen</h2>
        <p>Klik op een student om deze te bekijken</p>
        <hr />
        <select class="form-control">
            <option>Selecteer project</option>
            @foreach (BarometerDataAccesLayer.Project project in Model.OwnProjects)
            {
                <option value="@project.id">@project.name</option>
            }
        </select>
        <br />
        <br />
        <div class="panel-group" id="accordion">
            @{int counter = 0;}
            @foreach (KeyValuePair<string, IEnumerable<BarometerDataAccesLayer.User>> group in Model.UsersInGroups)
            {
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            @Html.ActionLink(group.Key, null, null, new { @data_toggle = "collapse", @data_parent = "#accordion", @Href = "#group_" + counter })
                        </h4>
                    </div>
                    <div id="group_@counter" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table table-bordered table-members table-centered">
                                <tbody>
                                    @foreach (BarometerDataAccesLayer.User user in group.Value)
                                    {
                                        <tr>
                                            <td>
                                                <img src="../../images/pf.jpg" alt="..." class="img-circle"></td>
                                            <td>@user.firstname @user.lastname</td>
                                            <td>@Html.ActionLink(" ", "Student", "Admin", new { user.id }, new { @class = "glyphicon glyphicon-eye-open", @Title = "Bekijk historich overzicht" })</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                                    counter++;
            }


        </div>

    </div>
    <div class="col-lg-6">
        <h2>Zoek een student</h2>
        <p>Typ het studentnummer van een student in om het overzicht te bekijken</p>
        <hr />
        @using(Html.BeginForm("StudentForm","Admin",FormMethod.Post)){
            <div class="form-group">
                <label class="control-label">Zoek student</label>
                <input type="text" class="form-control" name="student" />
            </div>
        }


    </div>
</div>

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Admin/Detail.cshtml
@{
    ViewBag.Title = "Detail";
}
<div class="row">
    <div class="col-lg-12">
        <h2>Project barometer</h2>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-lg-5">
        @using (Html.BeginForm("Detail", "Project", FormMethod.Post, new { @class = "form-vertical", @role = "form" }))
        {
            <div class="form-group">
                <label class="control-label">Naam</label>
                @Html.TextBox("naam", "Wordfeud", new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label class="control-label">Omschrijving</label>
                @Html.TextArea("omschrijving", "", new { @class = "form-control", @placeholder = "Waar gaat het project over?" })
            </div>
            <div class="form-group">
                <label class="control-label">Begin datum</label>
                <input type="date" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Eind datum</label>
                <input type="date" class="form-control">
            </div>
            <div class="form-group">
                <label class="control-label">Groepsindeling</label>
                <input type="file" class="form-control" name="groepsindeling" />
                <span class="help-block">Toegestaande bestanden : .xls, xlsx</span>
            </div>
            <hr />
            <div class="form-group">
                <label class="control-label">Beoordelingstemplate</label>
                <select class="form-control">
                    <option></option>
                    <option>Beoordelingstemplate standaard</option>
                    <option>Beoordelingstemplate leidinggeven</option>
                    <option>Beoordelingstemplate sociaal</option>
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Beoordelings momenten</label>
                <div class="row">
                    <div class="col-xs-5">
                        <input type="date" class="form-control" />
                    </div>
                    <div class="col-xs-5">
                        <input type="date" class="form-control" />
                    </div>
                    <div class="col-xs-2">
                        @Html.ActionLink(" ", null, null, new { @class = "btn btn-default glyphicon glyphicon-plus", @Href = "#" })
                    </div>
                </div>
            </div>

            <hr />
            <div class="form-group">
                <input type="submit" value="Opslaan" class="btn btn-primary" />
            </div>


        }
    </div>
</div>

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Admin/List.cshtml
@model Barometer_ASP_NET.Wrappers.AdminDashboardWrapper
@{ 
    ViewBag.Title = "Lijst";
}
<div class="row">
    <div class="col-lg-12">
        <h2>Projecten</h2>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>Titel</td>
                    <td>Aangemaakt door</td>
                    <td>Status</td>
                    <td>Week</td>
                    <td>Groepen</td>
                    <td>Wijzig</td>
                    <td>Verwijder</td>
                </tr>
            </thead>
            <tbody>
                @foreach (BarometerDataAccesLayer.Project project in Model.OwnProjects)
                {
                    <tr>
                        <td>@project.name</td>
                        <td></td>
                        @switch (project.status_name)
                        {
                            case "Active":
                            <td><span class="label label-success">Actief</span></td>
                                break;
                            case "Closed":
                            <td><span class="label label-success">Afgelopen</span></td>
                                break;
                            case "Pending":
                            <td><span class="label label-success">Aangemaakt</span></td>
                                break;
                            default:
                            <td><span class="label label-success">Onbekend</span></td>
                                break;
                        }
                        <td>@{int weeks = 0;} @if (project.status_name == "Active") { weeks = (int)((DateTime.Now).Subtract((DateTime)project.start_date).TotalDays) / 7; }@weeks</td>
                        <td>@Html.ActionLink(" ", "ListProjectGroup", "Admin",new {projectId = project.id}, new { @class = "glyphicon glyphicon-align-justify" })</td>
                        <td>@Html.ActionLink(" ", "Detail", "Admin",new {projectId = project.id}, new { @class = "glyphicon glyphicon-edit" })</td>
                        <td>@Html.ActionLink(" ", "DeleteProject", "Admin",new {projectId = project.id}, new { @class = "glyphicon glyphicon-remove"})</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Admin/ListProjectGroup.cshtml
@model Barometer_ASP_NET.Wrappers.AdminProjectGroupListWrapper
@{ 
    ViewBag.Title = "Lijst";
}
<div class="row">
    <div class="col-lg-12">
        <h2>Projecten</h2>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>Titel</td>
                    <td>ProjectNaam</td>
                    <td>Tutor</td>
                    <td>Eindcijfer</td>
                    <td>Details</td>
                    <td>Verwijder</td>
                </tr>
            </thead>
            <tbody>
                @foreach (BarometerDataAccesLayer.ProjectGroup group in Model.ProjectGroups)
                {
                    <tr>
                        <td>@group.group_code</td>
                        <td>@group.Project.name</td>
                        <td>@group.User.firstname @group.User.lastname</td>
                        <td>@group.group_end_grade</td>
                        <td>@Html.ActionLink(" ", "ProjectGroups", "Admin",new {groupId = group.id}, new { @class = "glyphicon glyphicon-edit" })</td>
                        <td>@Html.ActionLink(" ", "DeleteProject", "Admin",new {groupId = group.id}, new { @class = "glyphicon glyphicon-remove"})</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Barometer VS Project/Barometer_ASP_NET/Barometer_ASP_NET/Views/Admin/ProjectGroups.cshtml
@model Barometer_ASP_NET.Wrappers.AdminProjectGroupViewWrapper

@{
    ViewBag.Title = "Projectgroep";
}
<div class="row">
    <div class="col-lg-12">
        <h2>Groep 42INSO06b</h2>
        @Html.ActionLink("Terug naar het groepen overzicht", "ProjectGroups", "Admin", new { @class = "glyphicon glyphicon-arrow-left" })
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <h3>Student toevoegen</h3>
        <hr />

        @using (Html.BeginForm("AddStudent", "Admin", FormMethod.Post, new { @class = "form-vertical", @role = "form" }))
        {
            <div class="form-group">
                <label>Studentnummer</label>
                <input type="text" class="form-control" name="student" placeholder="Studentnummer" />
            </div>
            @Html.Hidden("projectID", Model.projectID)
            @Html.Hidden("groupID",Model.projectGroup)
            <div class="form-group">
                <button type="submit" class="btn btn-default">Toevoegen aan groep</button>
            </div>
        }

    </div>
    <div class="col-lg-6">
        <h3>Student overzicht</h3>
        <hr />
        @using (Html.BeginForm("ListStudents", "Group", FormMethod.Post, new { @class = "form-vertical", @role = "form" }))
        {
            List<SelectListItem> ownerItems = new List<SelectListItem>();
            foreach (BarometerDataAccesLayer.User owner in Model.CurrentProjectOwners)
            {
                ownerItems.Add(new SelectListItem {Text = owner.lastname + " " +owner.lastname, Value = owner.id.ToString() });
            }
            
            <div class="form-group">
                <label class="control-label">Tutor</label>
                <select class="form-control">
                    @Html.DropDownList("owner", ownerItems)
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Studenten</label>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td>Naam</td>
                            <td>Groep</td>
                            <td>Verwijder</td>
                        </tr>
                    </thead>
                    <tbody>
                        @{
            List<SelectListItem> selectItems = new List<SelectListItem>();
            foreach (BarometerDataAccesLayer.ProjectGroup group in Model.ProjectGroups)
            {
                selectItems.Add(new SelectListItem { Text = group.group_code.ToString(), Value = group.id.ToString() });
            }
                        }
                        @foreach (BarometerDataAccesLayer.User user in Model.GroupMemberUserList)
                        {
                            <tr>
                                <td>@user.firstname  @user.lastname</td>
                                <td>
                                    @Html.DropDownList("group", selectItems)
                                </td>
                                <td>@Html.ActionLink(" ", "RemoveStudent", "Group", new { @class = "glyphicon glyphicon-remove", @Href = "#" })</td>
                            </tr>
                        }

                    </tbody>

                </table>
            </div>
            <div class="form-group">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        }
    </div>
</div>